### ISSUE TITLE
Yuzu Early Access v2.0.4 not available!

### ISSUE THREAD

**Issue by SparkDrago05** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#14]
I am trying to download the latest version of the Yuzu Early Access launcher from this repository but whenever I download v2.0.4 after opening it I see that it is v2.0.3. I think you have accidentally uploaded the previous version instead of v2.0.4. Please update it soon!

**Comment by 1900forever** [comment]
same issue here

**Comment by HimDek** [comment]
You don't to download it from here. If you have an older version it will update itself.

What is happening with you is. The 2.0.4 you downloaded runs the previously installed 2.0.3.

And if 2.0.3 is saying that it can't connect to internet. This is because it is unable to download metadata from the previous source. In this case, please right click the launcher shortcut and open containing folder. Then delete and replace the old "yuzu Early Access Launcher.exe" with the new one and rename the new one same as the old one.
