### ISSUE TITLE
Updater won't work anymore

### ISSUE THREAD

**Issue by kaerusu** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#15]
Updater won't work
![image](https://github.com/HiDe-Techno-Tips/yuzu-Early-Access-Launcher/assets/27588211/091a295e-ca45-48a0-bd1b-36d4e5cb2947)
 anymore pretty much resumes it.

**Comment by HimDek** [comment]
If version 2.0.3 is saying that it can't connect to internet. This is because it is unable to download metadata from the previous source. In this case, please right click the launcher shortcut and open containing folder. Then delete and replace the old "yuzu Early Access Launcher.exe" with the new one downloaded from [here](https://github.com/HiDe-Techno-Tips/yuzu-Early-Access-Launcher/releases) and rename the new one same as the old one.
